### ISSUE TITLE
[FEATURE] Preset for extremely common date format(s)

### ISSUE THREAD

**Issue by Davve37** [April-Gras/obsidian-auto-timelines#124]
1. It's incredibly common that people write dates formatted as "17th of January 2015". I'd argue it's so common that it should be really easy to configure with perhaps a preset option, to turn the data string "YYYY-MM-DD" into "DDth of mmmm YYYY". This present need to be able to accurate handle st, nd, rd exceptions.

2. I also think there should be some consideration for whether or not this should be 0-indexed or 1-indexed, especially when it comes to the months and days, as most people consider the first day of the first month to be "01-01", not "00-00".

3. I think there should be an easy option/functionality to leave one of the date-types out. Sometimes events are not precise down to the day, and you might see dates such as "March 2014", or if the year is apparent by context; "23rd of July".

**Comment by DesertMirag3** [comment]
> Hi @April-Gras, I'm excited for this update, been looking forward to it for a while!
> 
> It does look like Kythorn is missing from the Calendar of Harptos preset, though?

Additionally:

1. It may be worth considering the intercalary months (holidays) of:
- Midwinter
- Greengrass
- Midsummer
- Highharvestide
- Feast of the Moon

2. This would create the full list of 17 "months":

| Calendar of Harptos |
| ---- |
| 1 - Hammer |
| 2 - Midwinter |
| 3 - Alturiak |
| 4 - Ches |
| 5 - Tarsakh |
| 6 - Greengrass |
| 7 - Mirtul |
| 8 - Kythorn |
| 9 - Flamerule |
| 10 - Midsummer |
| 11 - Eleasis |
| 12 - Elient |
| 13 - Highharvesttide |
| 14 - Marpenoth |
| 15 - Uktar |
| 16 - Feast of the Moon |
| 17 - Nightal |
