### ISSUE TITLE
[BUG] Inline events picking up text from all events under it

### ISSUE THREAD

**Issue by lingelbachmb** [April-Gras/obsidian-auto-timelines#134]
**Describe the bug**
When using inline events within the same note, events after another event are picking up the subsequent event's text

**To Reproduce**
Put something like this in a note:
`%%aat-inline-event
aat-event-start-date: 54
aat-event-end-date: true
aat-render-enabled: true
timelines: [inline-events]
%%
This is the first inline event text. 

Same goes with pictures.
![|180](https://images.unsplash.com/photo-1571988840298-3b5301d5109b?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=687&q=80)

%%aat-inline-event
aat-event-start-date: 76
aat-render-enabled: true
aat-event-title: This inline event has a overriden title
aat-event-picture: https://images.unsplash.com/photo-1541781774459-bb2af2f05b55
timelines: [inline-events]
%%

Second event text`

Then add a render on another note
`
```aat-vertical
inline-events 
```
`

and it shows the first event with text from event 2, while event 2 just shows event 2. They both show the entire note though on hover.

**Expected behavior**
Event 1 shows all text until it hits another inline event. I am not sure if this worked a different way before, but hovering the event would be ideal to show the location of the vent, instead of the note from the top.

**Screenshots**
![image](https://github.com/April-Gras/obsidian-auto-timelines/assets/612193/ba74cfbb-325f-43ef-81a1-2d82e90fb4f5)
![image](https://github.com/April-Gras/obsidian-auto-timelines/assets/612193/03a1b8c2-2f06-40ef-98c3-270bf9cde7be)
![image](https://github.com/April-Gras/obsidian-auto-timelines/assets/612193/dccbae6e-f3c1-4fa2-a635-f4a8bcab8e0c)

**Desktop (please complete the following information):**
 - Windows 11, using the sample vault from the repo

**Comment by April-Gras** [comment]
As a currently possible workaround:

Since https://github.com/April-Gras/obsidian-auto-timelines/releases/tag/0.12.2 you can force the body to stop using the end of body tag
You can edit that tag in the settings
![image](https://github.com/April-Gras/obsidian-auto-timelines/assets/1866440/4028c947-72e4-40ed-9d8c-281678c67e1c)
but by default it's set to `%%aat-event-end-of-body%%`

**Comment by lingelbachmb** [comment]
I updated to the latest and adding `%%aat-event-end-of-body%%` at the end of each block works to force it to stop scanning further for now. Thanks.
