### ISSUE TITLE
[FEATURE] Multiple Pieces of Properties in the Notes Section

### ISSUE THREAD

**Issue by giittyy** [April-Gras/obsidian-auto-timelines#138]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Be able to add more than one piece of frontmatter key to put in the notes section. Would also be cool to be able to label that data

**Describe alternatives you've considered**
Nothing. I guess just use the notes for notes.

**Comment by 0atman** [comment]
perhaps April will understand that but I didn't. Give some markdown examples with what formatting you'd like?

**Comment by April-Gras** [comment]
Same as @0atman, I wouldn't mind having some markdown / screenshot / drawing examples @giittyy

**Comment by giittyy** [comment]
I guess the correct term used in the app is the body. But the general principle could be set for the title as well. 

It's to have multiple property fields make up that field. Similarly to how in the date field you can have the year month and day make up the start time you could make the property keys {A} {B} {C} Make the body or title. Because if I want quick snapshot sometimes it's not just one piece of the property I want to view from the body or it's not just one property I want to make up the title. Hope that helps explain better.

**Comment by April-Gras** [comment]
You would want to fuse different properties into parts of your card if I understand correctly ?

**Comment by giittyy** [comment]
Yeah that’s a great way to put. I could only think it being useful for title and body.

**Comment by April-Gras** [comment]
I'm really not comfortable trying my hand at this.
I might reconsider this if your proposal was more detailed tho
I'll close this for now
