### ISSUE TITLE
[FEATURE] Settings Option to make the presence of the Fronmatter Key that initiates the (timelines) to be the true/false instead of "aat-render-enabled"

### ISSUE THREAD

**Issue by giittyy** [April-Gras/obsidian-auto-timelines#139]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
A toggle in the settings menu that uses the presence of the timelines key as a means to find the event instead of the separate key aat-render-enabled

**Describe alternatives you've considered**
Be able to edit the "aat-render-enabled" like users can with other keys.

**Comment by April-Gras** [comment]
That's easy enough, I'll wrap up the work on #124 then this will be done

**Comment by giittyy** [comment]
Awesome! Thank you!
