### ISSUE TITLE
[Help Wanted] More Information on String Date Token Types

### ISSUE THREAD

**Issue by thepancreator** [April-Gras/obsidian-auto-timelines#140]
I'm trying to set up timelines to use Calendar of Harptos month names, but I cannot figure out how to configure the String type tokens. The regex I'm using `(?<year>-?[0-9]*)-(?<month>-?.*)-(?<day>-?[0-9]*)` correctly matches the input I'm testing: `-30000-Mirtul-01`, but the output in the test pane shows "01 undefined -30000" (output formatting is `{day} {month} {year}`). I'm not sure what to put in the "Type the desired output of the token..." field. 
![image](https://github.com/April-Gras/obsidian-auto-timelines/assets/140094306/4bf76e8d-1f77-41b9-9b8d-60d39cd0b96a)
![image](https://github.com/April-Gras/obsidian-auto-timelines/assets/140094306/c79934e2-a82a-4e9a-a5cb-9e7ca38dd717)
Further, I can't even test a string value in the "month" test field. It only allows numbers.

**Comment by April-Gras** [comment]
In your first screenshot, It seems you need to add the name of the months to the list.
Careful to leave the first entry with a placeholder token if your date system doesn't have months starting at `0`
