### ISSUE TITLE
Calendar of Harptos Preset - Incomplete Month List

### ISSUE THREAD

**Issue by DesertMirag3** [April-Gras/obsidian-auto-timelines#142]
Hi @April-Gras, 

I'm excited for this update, been looking forward to it for a while!

It does look like Kythorn is missing from the Calendar of Harptos preset, though?

Additionally:

1. It may be worth considering the intercalary months (holidays) of:
- Midwinter
- Greengrass
- Midsummer
- Highharvestide
- Feast of the Moon

2. This would create the full list of 17 "months", and increase compatability with the Fantasy Calendar and/or Calendarium plugins by Javalent.

| Calendar of Harptos |
| ---- |
| 1 - Hammer |
| 2 - Midwinter |
| 3 - Alturiak |
| 4 - Ches |
| 5 - Tarsakh |
| 6 - Greengrass |
| 7 - Mirtul |
| 8 - Kythorn |
| 9 - Flamerule |
| 10 - Midsummer |
| 11 - Eleasis |
| 12 - Elient |
| 13 - Highharvesttide |
| 14 - Marpenoth |
| 15 - Uktar |
| 16 - Feast of the Moon |
| 17 - Nightal |

I easily edited the data JSON to apply these changes, and would be happy to provide it should you want it.

**Comment by April-Gras** [comment]
That missing month is a shame, I'll get it in ASAP

**Comment by DesertMirag3** [comment]
> That missing month is a shame, I'll get it in ASAP

Thank you! I also just noticed a few misspellings of other months: 

1. Eleasias > Eleasis
2. Merpenoth > Marpenoth

**Comment by April-Gras** [comment]
Already resolved myself to stick to copy pasting this time

I would love to have .zip of a vault that has events set on those intercalary dates just to see how the data is set and how I could support it best

The best info I got [was this](https://plugins.javalent.com/calendarium/create-calendar#Intercalary+or+month%3F), but it doesn't really tell me much

I'm under the impression I would need to write another update to handle intercalary months properly since just adding them at the end of the months would screw the sorting

**Comment by DesertMirag3** [comment]
If it would be helpful, I can get you a trimmed copy of my vault. I have an event that spans an intercalary month.

I wasn't able to glean much from that either; from my time using Fantasy Calendar, I know the months are set up individually upon choosing the preset from the plugin.

![Javelent Fantasy Calendar Months](https://github.com/April-Gras/obsidian-auto-timelines/assets/155386094/f4eb0e52-d2d9-44e2-a36c-846849d0dbc3)

From the minimal testing I've done, each of the intercalary months (that are 1 day long each), I've needed to use the fc-date and fc-end frontmatter to get events to span properly.

I just created a fork and added a file: dndCalendarOfHarptosDalereckoningExtendedDatePreset.ts, that has all of the months in the correct order and spelling. I've not submitted a pull request before, so not quite sure where to go from here?

**Comment by April-Gras** [comment]
Very nice of you to go trough the trouble of getting a fork set up
Also
> I'm under the impression I would need to write another update to handle intercalary months properly since just adding them at the end of the months would screw the sorting

I got a bit confused about the list, the order won't be screwed because of your additions and they are already part of [the latest patch](https://github.com/April-Gras/obsidian-auto-timelines/releases/tag/0.13.1)

**Comment by DesertMirag3** [comment]
Wow, that was fast! Thanks, April! Let me know if you want a trimmed .zip of my vault for examples of spanning events?

**Comment by April-Gras** [comment]
> Wow, that was fast! Thanks, April! Let me know if you want a trimmed .zip of my vault for examples of spanning events?

I would actually take it for testing purposes, doesn't need to be trimed (except if you don't feel comfortable uploading that)
