### ISSUE TITLE
Time bars fail to appear/align on timeline

### ISSUE THREAD

**Issue by ericdun89** [April-Gras/obsidian-auto-timelines#15]
![image](https://github.com/April-Gras/obsidian-auto-timelines/assets/39979723/01eb65d8-8641-4ce5-8ec1-81d538de3d11)
A longer timeline results in the time bars beginning to fail or misalign, as in the attached screenshot. I am not sure what is causing this issue, but I can verify that the referenced notes all follow the same format, which works without issue at the beginning of the timeline, but breaks down starting at the 6th timeline item.

**Comment by April-Gras** [comment]
Would be very grateful to get my hands on the complete list of dates, if not for the actual notes, used in the timeline.
Would make the debugging process easier

**Comment by ericdun89** [comment]
[Timeline.zip](https://github.com/April-Gras/obsidian-auto-timelines/files/11455768/Timeline.zip)
Sure thing! I have sent along the notes, the timeline, and a screenshot of my settings, as I have changed those, as well.

Thank you so much!
