### ISSUE TITLE
[FEATURE] Omit first heading in note content

### ISSUE THREAD

**Issue by iamrecursion** [April-Gras/obsidian-auto-timelines#182]
**Is your feature request related to a problem? Please describe.**
My notes tend to have both a name and an H1 heading that matches that name. In the rendered block this means that the title is repeated again in the content, which looks quite funky.

**Describe the solution you'd like**
I'd love to be able to omit the first H1 in the note content.

**Describe alternatives you've considered**
I am currently hacking around this by using CSS. 

**Additional context**
N/A

**Comment by April-Gras** [comment]
Heya @iamrecursion 

Came up with a per line ignore comment feature
By default it's set to `aat-ignore-line` but as always it's editable in the general settings of the plugin

Hope this enhancement suits your needs, here's a little preview of it in action:

[Screencast from 19-07-2024 00:30:46.webm](https://github.com/user-attachments/assets/226b2612-7d5c-4e3a-8274-b0747c707eed)

**Comment by iamrecursion** [comment]
Oh this is fantastic! Thank you so much!
