### ISSUE TITLE
[BUG] Render Toggle does not appear to work for inline events

### ISSUE THREAD

**Issue by leff** [April-Gras/obsidian-auto-timelines#184]
## Describe the bug

I'm trying to turn off inline events without just deleting them. It's not working for me. I expect that setting `aat-render-enabled` to `false` should exclude the inline event from displaying, but I'm still seeing it. `aat-render-enabled: false` does work for full page notes.

(I'm guessing it could be something like, when parsing inline events the false is coming through as the string `"false"`, which is of course `true` in javascript. I haven't looked at the code, but this kind of thing has bitten me in the past)

## To Reproduce

1. Add an inline event to a note
2. Set `aat-render-enabled: false` (or whatever you've set the Render Toggle Key to be)
3. Make a timeline block that includes inline event's timeline

### Expected behavior

The inline event is _not_ shown on the timeline

### Actual behavior

The inline event is shown on the timeline.

## Screenshots

On the left we see the source inline notes with render set to false, but we see the events big and bold in the timeline on the right.

<img width="1369" alt="Screenshot 2024-08-26 at 11 07 46 AM" src="https://github.com/user-attachments/assets/d8949358-7f72-404f-8b2f-b07824c1a51b">

## Desktop (please complete the following information):
 - OS: MacOS 14.6.1 (M1 chip)

**Smartphone (please complete the following information):**
- Not tested

**Comment by April-Gras** [comment]
Hey @leff 
Thank you so much for bringing this up
It should be fixed now

Let me know if anything else crops up

[Screencast from 26-08-2024 23:03:25.webm](https://github.com/user-attachments/assets/fb261e0a-7962-4a39-b28a-55a9730403e6)
