### ISSUE TITLE
Issue with Fantasy Calendar

### ISSUE THREAD

**Issue by ObsidianTTRPGProject** [April-Gras/obsidian-auto-timelines#21]
The Fantasy Calendar button is causing the start date to change to **fc-start** but it should be **fc-date**. My Obsidian was locking up when trying to render with fc-start.

**Comment by April-Gras** [comment]
Do you have a rough estimate of the number of notes you have ?

**Comment by April-Gras** [comment]
Fixed the key issue, but still curious about that performance issue :pray
