### ISSUE TITLE
Doesn’t work timeline

### ISSUE THREAD

**Issue by toomij** [April-Gras/obsidian-auto-timelines#25]
Created two files exact as REDME.md. Then created new note with ```aat-vertical…. Press “reading view” but nothing was displayed 
![86A14071-0A10-4615-B513-936AF7D266B5](https://github.com/April-Gras/obsidian-auto-timelines/assets/7142245/f35f5499-bb59-410c-acc9-2b2a299c7cdf)
![3F278C58-F4C2-4552-9083-68AAEAF9D22E](https://github.com/April-Gras/obsidian-auto-timelines/assets/7142245/9f611171-63f5-415d-9291-8802573b3077)
![8F096068-C444-44CC-BC2D-FE09F8EC3448](https://github.com/April-Gras/obsidian-auto-timelines/assets/7142245/1e1d3322-d177-46a4-868f-85a6e10550f5)
![7AF15910-E3F8-47A7-BE54-6A26C7A068B3](https://github.com/April-Gras/obsidian-auto-timelines/assets/7142245/63126b72-cf8f-4afb-aec3-f1e08e25d36c)
![3F65E072-ECB3-4D41-B970-72A8C0A85AA1](https://github.com/April-Gras/obsidian-auto-timelines/assets/7142245/73a4df5c-a981-4e15-ab9b-ccdd46dad9bb)

**Comment by April-Gras** [comment]
Strange
Just to get the obvious out of the way
Are you sure you enabled the plugin after installing ?
You mind sharing what device you're using ?
Thanks in advance

**Comment by toomij** [comment]
Enabled. 
iOS 16.3.1 (20D67)
iPhone 13 Pro Max

**Comment by April-Gras** [comment]
It also looks like the metadata in your nite is not wrapped in between `---`
[Obsidian documentation on metadata](https://help.obsidian.md/Editing+and+formatting/Metadata)

**Comment by toomij** [comment]
Thanks a lot. This is help for me.
