### ISSUE TITLE
Multi-word timelines

### ISSUE THREAD

**Issue by Folkemunne** [April-Gras/obsidian-auto-timelines#29]
It would be very nice if you could use multiple words in a timeline description, separated by a comma, so that if instance if I have an event that takes place featuring John Doe in New York, I can mark it so it appears in both their respective timelines without having to remember whether I cammelCased it or whatnot.

**Comment by Folkemunne** [comment]
Right! So as an example, I have an event for the 1996 Copenhagen Airport shooting between Hells Angels and Bandidos. I have pages collecting notable events for each of the clubs, as well as Copenhagen in general, so I want the event to show up in three distinct timelines: "Copenhagen", "Bandidos", and "Hells Angels". (Each of these have notable events that don't involve the other three.

Right now my frontmatter looks like this:

`timelines: [Bandidos, HellsAngels, Copenhagen]`

but I would like for it to be able to look like this:

`timelines: [Bandidos, Hells Angels, Copenhagen]`

**Comment by April-Gras** [comment]
All done @Folkemunne, don't hesitate to tell me if you run into some issues

Now you can separate tags in timelines just ike this

![](https://user-images.githubusercontent.com/1866440/241799416-78de88e6-7048-47a6-b943-fe7bbae58c69.png)

And if `,` is not your cup of tea you can go in the settings and change the split token in there

**Comment by Folkemunne** [comment]
Thank you very much!
