### ISSUE TITLE
[feature] Use hour and minutes in modern calendar

### ISSUE THREAD

**Issue by silentjames** [April-Gras/obsidian-auto-timelines#31]
Hello April!
First of all, thank you for all your effort in development of this amazing plugin! I'm sure it helps a lot of people (and me, of course) :)
Secondly, don't know is it a feature request or not, but:
My I use this plugin to track events (in real life or TTRPGs) using our current calendar and especially some events within one day? I'm asking because:
- I've designed regex `(?<year>-?[0-9]*)-(?<month>-?[0-9]*)-(?<day>-?[0-9]*) (?<hour>-?[0-9]*):(?<minute>-?[0-9]*)` for date and time, but for 12:00 I've getting 12:0;
- would be great to have an opportunity to covert `2023/06/06` to `June 6, 2023`, or `6 Jun 2023`, or `June 6th, 2023`, or their British analogue, you name it!

Thanks again!

**Comment by April-Gras** [comment]
Hey @silentjames,

Deep down, when finishing up on the flexible date system, a part of me knew some people would want to have even more control on the display format.

Regarding the hours display and the month display I'm not sure how to really go about it, but the idea is something I could implement.

Just in case you tought your regex was the problem, it's not. Just the display format system doesn't account for more formatting.

Progress on this will be trackable from [this branch](31-feature-use-hour-and-minutes-in-modern-calendar).

Thanks for your interest in the plugin, this is a great suggestion

**Comment by April-Gras** [comment]
Hey @silentjames 
It really took some thinking and a whole lot of time.
But I'm pretty sure the implemented system in #44 really fills all your little needs
Hope you like it.
It should be available in obsidian as of now

https://github.com/April-Gras/obsidian-auto-timelines/assets/1866440/f201d591-316a-4a86-a1d4-7ac956e381a9

**Comment by silentjames** [comment]
Thank you, you're the goddess! Updated, and will use it in all my campaigns!
