### ISSUE TITLE
Request: ITS Theme Toggle

### ISSUE THREAD

**Issue by ProStashio** [April-Gras/obsidian-auto-timelines#32]
Had a conversation on Discord, but here is the issue:

I know this is totally of my own doing, but I was curious if there would be a way that I could disable my ITS for the timeline? Or have more control over it? Not sure I am a fan of what I use in my vault for this.

![image](https://github.com/April-Gras/obsidian-auto-timelines/assets/19267479/17da91b2-305f-4dce-9da4-62963690a1e5)

**Comment by April-Gras** [comment]
Hey @ProStashio finally got to find a little time to look at this
It seems I would need a sample vault to work properly on this
I'm very un familliar with ITS and I feel it would be a great starting point for this issue

Thank you so much in advance, I know it can be a drag :sweat_smile:

**Comment by ProStashio** [comment]
Hey @April-Gras seems like the most recent ITS update fixed my issues here. All seems well now from what I can tell! Just found out a few mins ago funnily enough 😅

Sorry to waste your time!
