### ISSUE TITLE
Handling a variety of timeline scales

### ISSUE THREAD

**Issue by Aereanor** [April-Gras/obsidian-auto-timelines#37]
**The Issue**
Sometimes it is useful to be granular in timelines, such as when focussing on events that happen at very specific times, e.g. a timeline of political events during a month-long crisis.

At other times, it is useful to have a more general date when the scale of the timeline is much larger or when an event is less defined, e.g. "1066 - The Battle of Hastings" in a timeline of the formation of England as a nation, or "August 1974 - Negotiations begin to break down"

**Proposed Solutions**
I propose two solutions that could be implemented individually or to complement one another:

- Allow timelines to have a date format individually defined. Timelines without this definition will use the default format from the plugin settings. Otherwise, the user can define that events should be displayed as e.g. "YYYY" only or "MM-DD", etc. All events in the timeline will be truncated to that format
- If an event date field (e.g. year, month, date) is defined as "0" or some other non-value, do not attempt to display that field in any timeline the event is in. 
  - e.g. If an event is defined as "1912-08-00" it will only be rendered as "1912-08" in timelines.

**Comment by April-Gras** [comment]
These are two very senssible ideas, thank you so much for proposing those.
Right now my main focus is on https://github.com/April-Gras/obsidian-auto-timelines/issues/31

But I don't see why these two ideas could not be included in the plugin in the future

**Comment by April-Gras** [comment]
Hey @Aereanor 

I stopped trying to impleent anything for this
> If an event date field (e.g. year, month, date) is defined as "0" or some other non-value, do not attempt to display that field in any timeline the event is in.
e.g. If an event is defined as "1912-08-00" it will only be rendered as "1912-08" in timelines.

Ended up being way out of scope, might revisit the concept on a later day but for now this first option
> Allow timelines to have a date format individually defined. Timelines without this definition will use the default format from the plugin settings. Otherwise, the user can define that events should be displayed as e.g. "YYYY" only or "MM-DD", etc. All events in the timeline will be truncated to that format

Should do perfectly

https://github.com/April-Gras/obsidian-auto-timelines/assets/1866440/95cd30f6-75a1-488c-ad54-0bd86a5e7060

It should be available on obsidian as of now
Hope you find the update useful
