### ISSUE TITLE
Timelines from tags

### ISSUE THREAD

**Issue by mabgriff** [April-Gras/obsidian-auto-timelines#38]
I would like to be able to generate timelines that include all events in notes with a particular tag. Currently the equivalent is the "timelines:" metadata, but this duplicates tags in my use case.

I have notes for TTRPG individual sessions. Each session is tagged with the characters that participated. If I wanted to create a timeline to show the history of a particular character, I would have to manually go back through every note tagged with that character and add a new timeline name. The same idea applies to timelines for locations, etc.

Generating by tag would allow creating timelines without having to go back and edit metadata when creating a new timeline. The event already has its date info, so I could pull it into new timelines on the fly based on my existing tags.

Thank you for making this plugin!

**Comment by April-Gras** [comment]
Hey @mabgriff, this is a cool idea
Would you mind sharing a sample vault for me to test this out, the bigger the better.

 > The event already has its date info, so I could pull it into new timelines on the fly based on my existing tags.

Do you mean it's already in the metadata for each note or is it also in the tags ?

**Comment by mabgriff** [comment]
[AAT Example Vault.zip](https://github.com/April-Gras/obsidian-auto-timelines/files/11929711/AAT.Example.Vault.zip)

Here's an example I created that includes the Fantasy Calendar plugin so that you can see exactly what I'm doing. I used the Gregorian calendar for ease of reading.

> Do you mean it's already in the metadata for each note or is it also in the tags ?

The metadata; since I've already added event metadata, the notes are ready for inclusion in a timeline other than not having the timeline name listed. Let me know if there's anything else I can provide/answer to help :)

**Comment by April-Gras** [comment]
Alright I think I got it, this a great tool that offers great flexibility
To enable tag lookup for timelines just head to the settings there's a new toggle in tere

https://github.com/April-Gras/obsidian-auto-timelines/assets/1866440/6c245258-fa0e-4d9b-b1eb-9d149f44c5c8

**Comment by mabgriff** [comment]
Just updated, it's working perfectly! Thank you again
