### ISSUE TITLE
Open Ended Events

### ISSUE THREAD

**Issue by Aereanor** [April-Gras/obsidian-auto-timelines#39]
**The Problem**
Some events are ongoing - they have a distinct range of time, but no end date is known yet.

When displaying these in a timeline, they either must be shown as a distinct event or as a range using a potential end date far in the future to ensure it reaches the end of the timeline.

**Proposed Solution**
Add a new "aat-event-ongoing" field, which if present and set to true will display such an event as "From StartDate to Present" and extend its range to the end of the timeline.

**Comment by April-Gras** [comment]
Wouldn't setting the end date to `true` do the trick ?

**Comment by Aereanor** [comment]
Yep! I missed that in the docs. My bad!
