### ISSUE TITLE
[Feature Request] Add a CI with Eslint to fix and push issues directly into the repo

### ISSUE THREAD

**Issue by Raboro** [April-Gras/obsidian-auto-timelines#41]
Right now this repo has no CI to automatically check the code when new commits are pushes. To add a CI together with Eslint would be a nice feature to guarantee a nice code style with no issues. This could be accomplished by adding a code style analysis directly in CI. Then on each push the code will be checked and it´s shown if there a any issues. This could be more efficient by directly fix those issues in CI and push them directly via CI into the repo. 

A Eslint configuration file: ``.eslintrc`` also already in the repo so it would be easy to use it. 
A couple of things need to be added:
1. Github Action worfklow (CI)
2. Two scripts used in the Action workflow to use eslint and check and fix the issues
3. Settings must allow pushes from the Github Action but.

**Comment by April-Gras** [comment]
Hey @Raboro thank you for taking interest in the project

Not sure I'll end up doing it since no one else is contributing right now, but who's to say what the future will hold

If it's something that actually prevents you from contributing then I guess now would be a good time for me to setup GitHub actions to run those checks

**Comment by Raboro** [comment]
Thanks for the reply.
I think generalizing the code styling is a good idea if other people want to contribute. Also it only takes a few minutes to set up automation for this. Or even using test automation is a good tool to make the project more secure and constantly testable. So before merging for example a pull request, if there is a problem the automated pipeline will fail.
