### ISSUE TITLE
Non-Note Events

### ISSUE THREAD

**Issue by Aereanor** [April-Gras/obsidian-auto-timelines#45]
**The Problem**

Some events are defined in relation to other notes, and so requiring their own note causes bulk and overhead. For example:

- There is a leader of a state who has a note describing them. They have various dates associated with them, including birth, death, their first election where they lost, the next election where they won, the date they took office, the date they left office, etc.. To include these on a timeline, the user must create new notes for each of these events (some may be notes with start and end dates).

**Proposed Solution**

Parse existing notes for a new block, which could be defined similarly to (e.g.) for the above example:

'''aat-event
[Name of Timeline 1, Name of Timeline 2]
name: Birth of Alex Person
start-date: 01-01-1950
'''

'''aat-event
[Name of Timeline 1, Name of Timeline 2]
name: 1990 Election Loss
start-date: 01-01-1990
desc: Took only 5% of the vote
'''

'''aat-event
[Name of Timeline 1, Name of Timeline 2]
name: 2005 Election Win
start-date: 01-01-2005
desc: Won with 95% of the vote
'''

'''aat-event
[Name of Timeline 1, Name of Timeline 2]
name: 2010 Election Loss and Leaves Office
start-date: 01-01-2005
desc: Lost with only 10% of the vote
'''

'''aat-event
[Name of Timeline 1, Name of Timeline 2]
name: Death of Alex Person
start-date: 01-01-2020
desc: Died of natural causes
'''

In this way, multiple events directly relating to a single note can be defined inline and appear on timelines. The card produced could be unclickable, or could be anchored to where the event is defined within the note.

**Comment by April-Gras** [comment]
Damn, this is another great idea.
I will most definitly end up implementing this.

For the moment I need to polish up #31 then move on to your previous feature request (#37)
So this will definitly take up some time, but thank you so much for this :pray:

**Comment by April-Gras** [comment]
Hey @Aereanor I'm very much overjoyed to tell you that
Inline notes are now available in version [0.7.0](https://github.com/April-Gras/obsidian-auto-timelines/releases/tag/0.7.0). It was a bit of an undertaking but the end result is really worth it

https://github.com/April-Gras/obsidian-auto-timelines/assets/1866440/454c04c0-8739-4376-8904-90fd4c4551a1

I'm sure you'll get some good use out of it
Thank you again for the submission, lmk if anything goes wrong

**Comment by Aereanor** [comment]
Hi @April-Gras, thank you for yourwork into this and my other suggestions. I am very grateful for your efforts.
