### ISSUE TITLE
More documentation

### ISSUE THREAD

**Issue by Gourav1910** [April-Gras/obsidian-auto-timelines#48]
Please make a demo vault in which everything is setup and atleast a demo video to use it properly. The plugin could be amazing but why create resistance for user to use it? Documentation should be more visual.

**Comment by April-Gras** [comment]
There is actually a demo Vault [here](https://github.com/April-Gras/obsidian-auto-timelines#sample-vault-with-basic-examples) and Alternatively [Josh Plunkett](https://www.youtube.com/@JoshPlunkett) did [a tutorial video](https://www.youtube.com/watch?v=992o1j8zRSk) covering the basics

Some updates have been made since then so I guess getting more examples down could be welcome
Thanks for the heads up

**Comment by Gourav1910** [comment]
> There is actually a demo Vault [here](https://github.com/April-Gras/obsidian-auto-timelines#sample-vault-with-basic-examples) and Alternatively [Josh Plunkett](https://www.youtube.com/@JoshPlunkett) did [a tutorial video](https://www.youtube.com/watch?v=992o1j8zRSk) covering the basics
> 
> Some updates have been made since then so I guess getting more examples down could be welcome Thanks for the heads up

I checked your demo vault and it looks like a nice plugin. I found some issues.

1) Strips(the line that representing the date range) are not rendering right. I put different start date and same end date of two different notes so the strips should start at different location and end at same but it is not happening.
![image](https://github.com/April-Gras/obsidian-auto-timelines/assets/101202140/5d91a513-ea55-4818-9cca-c87d76432c89)

2) It is not live updating. We need to refresh the note

3) When I installed the plugin in my vault then it was not rendering the content of the note like it is doing in demo vault. In my vault it was saying the body content is missing even when I typed in the note below frontmatter.

Regarding documentation I saw lot of plugins show important links(videos and articles) and also an uploaded demo video on readme page so it is easy to instantly get the idea about what the plugin is. And also I think you should put the folder in code section for demo vault so people can instantly see here is a demo vault. But overall you did a great job. I like this plugin because I also write stories so it is easier to write various events in different notes but still we can see all in visual form at a single place.

**Comment by April-Gras** [comment]
> Strips(the line that representing the date range) are not rendering right. I put different start date and same end date of two different notes so the strips should start at different location and end at same but it is not happening.

This looks like an issue on it's own


> When I installed the plugin in my vault then it was not rendering the content of the note like it is doing in demo vault. In my vault it was saying the body content is missing even when I typed in the note below frontmatter.

Did you re-render the timeline ?


> It is not live updating. We need to refresh the note

True, there's no live updating, haven't come around doing that yet.
In the meantime entring and exiting the markdown code block does the trick


If you have the time and the will, you're welcome to open each of those as separate issues and perhaps I'll come around and attempt to handle them, they are all valid points, thank you for the feedback
