### ISSUE TITLE
Historical dates (A.D. and B.C. in a single timeline) do not sort properly

### ISSUE THREAD

**Issue by dfields16** [April-Gras/obsidian-auto-timelines#53]
Historical dates using B.C. and A.D. do not render or sort correctly. Support for this would be much appreciated.

**Current workaround:** 
Date parser regex: `(?<yearBC>-?[0-9]*)BC-(?<year>-?[0-9]*)-(?<month>-?[0-9]*)-(?<day>-?[0-9]*)`
Date parser group priority: yearBC,year,month,day
Date display format: {day}/{month}/{year}{yearBC}

**Comment by dfields16** [comment]
Hi @April-Gras, sorry for the late response. Attached is a sample vault. It has 3 notes. One for BC and 2 for AD. 
If you're open to suggestions, my thought on fixing it would be to allow for the date to be negative. Depending on the sign, the user could define a string to append to the year when displayed. So if the year were negative, a user could define a string "B.C." or if positive, "A.D."

Thanks for making this awesome plugin! 
[date-sample.zip](https://github.com/April-Gras/obsidian-auto-timelines/files/12268353/date-sample.zip)

**Comment by April-Gras** [comment]
https://github.com/April-Gras/obsidian-auto-timelines/assets/1866440/aa153243-1c05-41a8-8d5f-b575e05a19c4

Hey @dfields16,
Version [0.8.0](https://github.com/April-Gras/obsidian-auto-timelines/releases/tag/0.8.0) is out and available as of now.
You can now set condition based formats to any token. I included a little video of how to achieve `B.C.` and `A.D.` like you wanted to.

Hope you like the update and find some use out of it

**Comment by dfields16** [comment]
Thanks @April-Gras for the awesome work and instruction video. I just tried it out and it works great!

Have a great day!
