### ISSUE TITLE
[FEATURE] Same Date Sort Order

### ISSUE THREAD

**Issue by mwsmedia** [April-Gras/obsidian-auto-timelines#61]
I'm pulling serial fiction installments into the timeline. Each installment begins with a three digit number -- for example, "001 - Alex."  Several installments might occur on the same calendar day. When displayed on the timeline, they appear in reverse alphabetical order:

004 - Alex
003 - Lina
002 - Carson
001 - Alex

Note that it doesn't matter what order they're added.

**Describe the solution you'd like**
At a minimum, I'd like multiple events on the same day to appear on the timeline in ascending numberical / alphabetical order, 001 - 999 and A-Z.  Ideally, I'd like to be able to assign the order by which each event appears when there are multiple events on the same day. Blue sky: drag and drop on the timeline!

**Comment by April-Gras** [comment]
Hi @mwsmedia

Just to be sure, your current setup has multiple notes that points to the same exact time but they are not displayed in the order you wished them to ?

If that's the case, a quick workaround would be for you to add an additional date token at the end of the token chain in the settings and omit it from the output format.



Sorting the titles shouldn't be too hard to implement down the line.
Thank you so much for your input, hope it helps in the meantime

**Comment by mwsmedia** [comment]
Thanks for the quick reply!

It's that multiple notes point to the same date, not time, and they are displayed in reverse alphabetical order in the timeline. Reverse alphabetical order seems like an odd choice for the default display, no? The standard would be alphabetical order, one would think.  Was it a UX decision to do reverse alpha?

I don't understand your work-around... wouldn't I have to assign something to that additional date token in the frontmatter data item, even if it wasn't displayed? How would an empty date token effect the display order of the notes in the timeline?|

Thanks again!
