### ISSUE TITLE
[FEATURE] Separate size control for header and body font in timeline windows

### ISSUE THREAD

**Issue by Kuiriel** [April-Gras/obsidian-auto-timelines#66]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

Is there a simple command I can add to the styles.css file or to my snippets to shrink the size of the header and text only in the timelines, relative to the default?

I write my content in large font and usually read it in large font too. Like... the biggest font. This stops my brain being overwhelmed with how much I see. e.g. in Scrivener I'll work with only a few lines of text at a time.

However, when using features like Timelines, I do want to see more text as that's what such an overview is for. But my overly large font means I won't see more than 8 characters in the heading. It looks like it's using Headers 2 and 4 for its size.

**Describe alternatives you've considered**

I can stop being a dork and just unlock my mouse wheel and then scroll out at super speed to shrink the timeline, but it affects both main windows and all other text too.

**Additional context**

Your plugin looks awesome and I can understand how to use it because the instructions aren't backwards and upside down, thank you so much. I look forward to trying to make sense of my too many words.

**Comment by April-Gras** [comment]
Hey @Kuiriel,
Thank you for raising this issue.

As a quick workaround, I'm pretty sure some other plugins could allow you to add some custom styling to a note.

I'll just add a little option in the settings to force the font size of the different blocks to a amount of px of your choice, this should fix your issue I suppose

**Comment by April-Gras** [comment]
@Kuiriel latest update adds input fields to override the font sizes you wanted to change

https://github.com/April-Gras/obsidian-auto-timelines/assets/1866440/80c3ee71-2568-4a6c-be0d-b8ef7d4fa591

I hope this helps, lmk if anything goes wrong

**Comment by Kuiriel** [comment]
Wow, this is super considerate of you to have accommodated. Thank you so much!
