### ISSUE TITLE
[BUG] Since the latest update, the app freezes whenever it tries to render a timeline

### ISSUE THREAD

**Issue by Didie9** [April-Gras/obsidian-auto-timelines#67]
**Describe the bug**
I've tested the plugin (and loved it) 2 days ago and it worked perfectly. 
Since the latest update, it freezes the whole app and can't be used.

**Steps to Reproduce**
I install and enable the plugin -> Everything works.
I render an empty timeline -> it works.
I add one event to be rendered in the timeline -> it freezes the whole application (keyboard, cursor not responding).
Close/Reopen -> the app automatically freezes again.

**Workaround** 
Close the app.
Delete the april's automatic timeline in the plugins folder.
Reopen -> Everything works fine.

I'm on PC - Windows 10

**Comment by April-Gras** [comment]
Hey @Didie9 could you provide a .zip of a failing vault for me to have a starting point trying to debug this ?
Thank you for reporting this, looks quite bothersome

**Comment by Didie9** [comment]
I've tried creating a new vault, but can't reproduce the bug. 
However, I duplicated my failing vault, deleted all the plugins but yours, kept only the necessary pages to render the timeline and it still fails. 

Here's the .zip file: [AAT_Debug.zip](https://github.com/April-Gras/obsidian-auto-timelines/files/12599865/AAT_Debug.zip)

Thanks for looking into it!

**Comment by April-Gras** [comment]
The issue should be resolved now @Didie9 
Lmk if anything goes wrong
