### ISSUE TITLE
Date Display

### ISSUE THREAD

**Issue by ObsidianTTRPGProject** [April-Gras/obsidian-auto-timelines#7]
So can I just say I really like this plugin. It's simple and is very close to enabling something the community have chased for a while. Timeline + Fantasy Calendar integration!

To achieve integration I have changed the default settings for the following to match the Frontmatter used by the Fantasy Calendar plugin. 

![image](https://user-images.githubusercontent.com/96321415/236649214-0f1c211c-2846-4ad3-8e3c-77d4ce763e47.png)

I've noted however that the dates do not display in the Timeline. 

![image](https://user-images.githubusercontent.com/96321415/236649236-d1995178-bd0f-46f7-ab5b-f398fb1ca374.png)

If I leave the original datestart and dateend config in the Frontmatter then the date displays still. Is it possible the plugin is hardcoded to look at these fields for the displayed text?

![image](https://user-images.githubusercontent.com/96321415/236649286-bf70e1ce-a890-4627-8b8f-a5210d305a98.png)

This shows Frontmatter that does display a year in the render. 
![image](https://user-images.githubusercontent.com/96321415/236649290-a95ce8c0-d2b5-4f2b-a8ad-2f355b8e953e.png)

Also is there anyway to make it work with a full date? Right now if I use a calendar date '1491-01-20' the render fails to display the date. If I just put 1491 then it works fine. 

Thanks for your work on this I rather like it. I'm in the process of making an instructional video on all this.

**Comment by April-Gras** [comment]
Hey thank you for your interest in the project
The settings not being taken into account issue is no more.
But concerning the date format I think you might be right, I'll look into it and try to find an elegant and customizable solution.
Progress on that can be found here https://github.com/April-Gras/obsidian-auto-timelines/issues/9

**Comment by ObsidianTTRPGProject** [comment]
Thank you :) can confirm years are now displaying correctly. 
![image](https://user-images.githubusercontent.com/96321415/236651222-a96bd7b8-15d5-418d-9d62-c8e565a41cb5.png)
