### ISSUE TITLE
[FEATURE] Tag lookup for hierarchical tags

### ISSUE THREAD

**Issue by architaktus** [April-Gras/obsidian-auto-timelines#70]
**Is your feature request related to a problem? Please describe.**
The Plugin is cooool

**Describe the solution you'd like**
Obsidian supports hierarchical tags, but the timeline for now can only search for exact tags. It could be better when it could omit the child tag by searching

**Describe alternatives you've considered**
i.e.:
in md file: #A/B/C #X/Y/Z

by Tag lookup, for now this file can only be search by "A/B/C", "X/Y/Z" or both, but it would be great when user could do:
```aat-vertical
A/B, X
```

**Additional context**
thanks for the great Plugin!

**Comment by April-Gras** [comment]
Hey @architaktus, thanks for taking an interest in the plugin.
I puplished a new version that is available to download now.
That was an easy addition, let me know if anything goes wrong on your side
