### ISSUE TITLE
[BUG]searching Issue: nested tags

### ISSUE THREAD

**Issue by architaktus** [April-Gras/obsidian-auto-timelines#72]
**Describe the bug**
thanks for the new update! but it doesnt seem to do search as I expected

**To Reproduce**
I have Tags like: #A/B/C, #M/N, #X/Y/Z
timeline shows only for the first level tag (i.e. only works for A, M, X)

**Expected behavior**
what I expect is: timeline shows by searching `A/B, X/Y`

**Obsidian Version**
v1.4.14

**Comment by April-Gras** [comment]
Simple begavior:

![image](https://github.com/April-Gras/obsidian-auto-timelines/assets/1866440/b5bbbfc5-5773-4ef0-aad2-7f6e9fef05be)

More complex behavior, would it be the first timeline or the second ?
![image](https://github.com/April-Gras/obsidian-auto-timelines/assets/1866440/e1cf8106-b972-404b-bff3-46c759409b54)

**Comment by architaktus** [comment]
Timeline B is corret! as it should focus on the tags that contain "inbox/processing"
and only `inbox` could make a Timeline A 

and a little further example:
![grafik](https://github.com/April-Gras/obsidian-auto-timelines/assets/10756799/3b265cd9-4174-409c-a58a-e60d41c32693)
