### ISSUE TITLE
[BUG] Handling of markdwon path for images

### ISSUE THREAD

**Issue by YoSiJo** [April-Gras/obsidian-auto-timelines#93]
**Describe the bug**
It is not possible to use images with relative values.
It then remains empty or the next entry is used.

**To Reproduce**

````markdown

## Timeline

```aat-vertical
example
```

## Events

### Event 1

%%aat-inline-event
fc-date: 1006-07-22T00:00:00
fc-display-name: Event 1
aat-render-enabled: true
timelines: [example]
%%

![example](../../../attachment/event_1.jpg)

---

Foo

---

### Event 2

%%aat-inline-event
fc-date: 1006-09-19T00:00:00
fc-display-name: Event 2
aat-render-enabled: true
timelines: [example]
%%

![[../../../attachment/event_2.png]]

---

Baa

---

````

**Expected behavior**
Using of `event_1.jpg` on Event 1 and using of `event_2.jpg` on Event 2.
Current and wrong: Using of `event_2.jpg` on Event 1 and using of `event_2.jpg` on Event 2.

**Screenshots**

![grafik](https://github.com/April-Gras/obsidian-auto-timelines/assets/42408075/abb872cd-0740-45ee-ab28-4251bd201e5f)
![grafik](https://github.com/April-Gras/obsidian-auto-timelines/assets/42408075/b753f835-7b0a-4960-b8a3-da9c36f57317)

**Desktop (please complete the following information):**
 - OS: Linux

**Comment by April-Gras** [comment]
Hey @YoSiJo thank you for taking the time to report this
I went over this and you've stumbled upon a really sneaky bug.
For now as a workaround you could replace this
```md
![Mammut 3D](../../../attachment/Portraits/Tiere/Mammut/Mammut%203D.jpg)
```
to something like this using [the obsidian internal file embed syntax](https://help.obsidian.md/Linking+notes+and+files/Embedding+files#Embed+an+image+in+a+note)
```md
![[../../../attachment/Portraits/Tiere/Mammut/Mammut%203D.jpg]]
```
Hope this helps in the meantime

**Comment by April-Gras** [comment]
@YoSiJo I just released a patch, let me know if the issue still perssists after updating to [v0.11.1](https://github.com/April-Gras/obsidian-auto-timelines/releases/tag/0.11.1)

**Comment by YoSiJo** [comment]
Thank you very much for solving the error and processing it so quickly.
