### ISSUE TITLE
[FEATURE]: Using Calendarium and span elements for inline event creation.

### ISSUE THREAD

**Issue by namtrah** [April-Gras/obsidian-auto-timelines#95]
**Is your feature request related to a problem? Please describe.**
This is not related to a problem, AFAIK. First, I guess the feature should say to implement The Calendarium timeline approach, but that can be done manually at first. 

The Calendarium, has just added `<span>` element to inline event creation. Would it be possible that the Auto Timelines also use this syntax?

**Describe the solution you'd like**
I would like to see integration between The Calendarium and Auto Timelines plugins to use `<span>` elements to define inline events.

**Describe alternatives you've considered**
Alternative is to use the outdated (and unmaintained) Obsidian Timelines plugin.

**Additional context**
See The Calendarium Git Hub [Repo](https://github.com/javalent/the-calendarium) and the Documentation's [explanation](https://plugins.javalent.com/calendarium/events/automatic#Span%20tag%20event%20creation) of `<span>` event creation.

**Comment by April-Gras** [comment]
Hey @namtrah I would love a sample vault, it would really help me out
Just a .zip of it would do perfect
