### ISSUE TITLE
[FEATURE]: Limiting the feed area 

### ISSUE THREAD

**Issue by YoSiJo** [April-Gras/obsidian-auto-timelines#97]
**Is your feature request related to a problem? Please describe.**
If the sentence is very short, the event text for an inline event often includes the upcoming headline.
As a result, I sometimes have to include filler text so that the next headline is not visible.

**Describe the solution you'd like**

I would like to be able to specify a kind of limitation mark.
For example, automatically the coming headline `^#` or the coming of a line with `---$`.
So that only the text above this marker is included.

**Describe alternatives you've considered**

An `aat-event-description` attribute; But the solution does not work well for me.

**Additional context**

Example in which event 1 also displays event 2 and the text.:

````markdown
# [Example Timeline](Example%20Timeline.md)

## Timeline

```aat-vertical
test
```

## Event

### Event 1

%%aat-inline-event
fc-date: 1006-07-22T00:00:00
fc-display-name: Event 1
aat-render-enabled: true
timelines: [test]
%%

Foo

### Event 2

%%aat-inline-event
fc-date: 1006-07-22T01:00:00
fc-display-name: Event 2
aat-render-enabled: true
timelines: [test]
%%

Baa

````

**Comment by April-Gras** [comment]
You can now use the default `%%aat-event-end-of-body%%` or edit it in the settings tab
